services:
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - 1883:1883
      - 9001:9001

    volumes:
      - ./PC/mosquittoData/config:/mosquitto/config
      - ./PC/mosquittoData/data:/mosquitto/data
      - ./PC/mosquittoData/log:/mosquitto/log
    
    stdin_open: true
    tty: true

  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: arqui2-database  # contraseña de root
      MYSQL_DATABASE: mqtt-sensores  # Crea la base de datos automáticamente
      TZ: America/Guatemala # Zona horaria
    ports:
      - "3306:3306"  # Mapea el puerto 3306 del contenedor al puerto 3306 de la máquina local
    volumes:
      - ./PC/DB/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysql", "-h", "localhost", "-uroot", "-parqui2-database", "-e", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
